=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/limes.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT LIMES (PREFIX*, SOURCE, TARGET, (METRIC | MLALGORITHM), ACCEPTANCE, REVIEW, EXECUTION*, GRANULARITY*, OUTPUT*)>
<!ELEMENT PREFIX (NAMESPACE, LABEL)>
<!ELEMENT NAMESPACE (#PCDATA)>
<!ELEMENT LABEL (#PCDATA)>
<!ELEMENT SOURCE (ID, ENDPOINT, GRAPH*, VAR, PAGESIZE, MINOFFSET*, MAXOFFSET*, RESTRICTION+, PROPERTY+, FUNCTION*, OPTIONAL_PROPERTY*, TYPE*)>
<!ELEMENT TARGET (ID, ENDPOINT, GRAPH*, VAR, PAGESIZE, MINOFFSET*, MAXOFFSET*, RESTRICTION+, PROPERTY+, FUNCTION*, OPTIONAL_PROPERTY*, TYPE*)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT RESTRICTION (#PCDATA)>
<!ELEMENT METRIC (#PCDATA)>
<!ELEMENT ACCEPTANCE (THRESHOLD, FILE, RELATION)>
<!ELEMENT REVIEW (THRESHOLD, FILE, RELATION)>
<!ELEMENT RELATION (#PCDATA)>
<!ELEMENT ENDPOINT (#PCDATA)>
<!ELEMENT GRAPH (#PCDATA)>
<!ELEMENT VAR (#PCDATA)>
<!ELEMENT CLASS (#PCDATA)>
<!ELEMENT PROPERTY (#PCDATA)>
<!ELEMENT OPTIONAL_PROPERTY (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT THRESHOLD (#PCDATA)>
<!ELEMENT FILE (#PCDATA)>
<!ELEMENT PAGESIZE (#PCDATA)>
<!ELEMENT MAXOFFSET (#PCDATA)>
<!ELEMENT MINOFFSET (#PCDATA)>
<!ELEMENT GRANULARITY (#PCDATA)>
<!ELEMENT OUTPUT (#PCDATA)>
<!ELEMENT FUNCTION (#PCDATA)>
<!ELEMENT EXECUTION (REWRITER*, PLANNER*, ENGINE*, OPTIMIZATION_TIME*, EXPECTED_SELECTIVITY*)*>
<!ELEMENT REWRITER (#PCDATA)>
<!ELEMENT PLANNER (#PCDATA)>
<!ELEMENT ENGINE (#PCDATA)>
<!ELEMENT MLALGORITHM  (NAME*, TYPE*, TRAINING*, PARAMETER*)*>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT TRAINING (#PCDATA)>
<!ELEMENT PARAMETER  (NAME*, VALUE*)*>
<!ELEMENT VALUE (#PCDATA)>
<!ELEMENT OPTIMIZATION_TIME (#PCDATA)>
<!ELEMENT EXPECTED_SELECTIVITY (#PCDATA)>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/dailymed-drugbank.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>daily</ID>
		<ENDPOINT>datasets/dailymed-drugbank-ingredients/source2.csv</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>name AS lowercase</PROPERTY>		
		<TYPE>CSV</TYPE>
	</SOURCE>
	<TARGET>
		<ID>drugbank</ID>
		<ENDPOINT>datasets/dailymed-drugbank-ingredients/target2.csv</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>name AS lowercase</PROPERTY>
		<TYPE>CSV</TYPE>
	</TARGET>
	
	<METRIC>AND(cosine(x.name,y.name)|0.146,AND(AND(trigrams(x.name,y.name)|0.49,jaccard(x.name,y.name)|0.65)|0.51,trigrams(x.name,y.name)|0.51)|0.51)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.55</THRESHOLD>
		<FILE>dailymed_drugbank_incredients_accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.4</THRESHOLD>
		<FILE>dailymed_drugbank_incredients_reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
		<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/PublicationData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>dblp2</ID>
		<ENDPOINT>datasets/DBLP-ACM/DBLP2.csv</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>title AS lowercase</PROPERTY>
		<PROPERTY>authors AS lowercase</PROPERTY>
		<PROPERTY>venue AS lowercase</PROPERTY>
		<!--<PROPERTY>year AS number</PROPERTY> --> 
		<TYPE>CSV</TYPE>
	</SOURCE>
	<TARGET>
		<ID>acm</ID>
		<ENDPOINT>datasets/DBLP-ACM/ACM.csv</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>title AS lowercase</PROPERTY>
		<PROPERTY>authors AS lowercase</PROPERTY>
		<PROPERTY>venue AS lowercase</PROPERTY>
		<!--<PROPERTY>year AS number</PROPERTY>-->
		<TYPE>CSV</TYPE>
	</TARGET>
	
	<METRIC>AND(cosine(x.title,y.title)|0.11,euclidean(x.year,y.year)|0.83)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.62</THRESHOLD>
		<FILE>pub_accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.5</THRESHOLD>
		<FILE>pub_reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/Abt-Buy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>abt</ID>
		<ENDPOINT>datasets/Abt-Buy/Abt.csv</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>name AS lowercase</PROPERTY>
		<PROPERTY>description AS lowercase</PROPERTY>
		<PROPERTY>price AS number</PROPERTY>
		<TYPE>CSV</TYPE>
	</SOURCE>
	<TARGET>
		<ID>buy</ID>
		<ENDPOINT>datasets/Abt-Buy/Buy.csv</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>name AS lowercase</PROPERTY>
		<PROPERTY>description AS lowercase</PROPERTY>
		<PROPERTY>price AS number</PROPERTY>
		<TYPE>CSV</TYPE>
	</TARGET>
	
	<METRIC>jarowinkler(x.name,y.name)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.5431</THRESHOLD>
		<FILE>pub_accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	
	<REVIEW>
		<THRESHOLD>0.5431</THRESHOLD>
		<FILE>pub_reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
        <EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>

	<OUTPUT>N3</OUTPUT>
</LIMES>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/DBLP-Scholar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>dblp1</ID>
		<ENDPOINT>datasets/DBLP-Scholar/DBLP1.csv</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>title AS lowercase</PROPERTY>		
		<PROPERTY>authors AS lowercase</PROPERTY>
		<PROPERTY>venue AS lowercase</PROPERTY>
		<PROPERTY>year AS number</PROPERTY>
		<TYPE>CSV</TYPE>
	</SOURCE>
	<TARGET>
		<ID>scholar</ID>
		<ENDPOINT>datasets/DBLP-Scholar/Scholar.csv</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>title AS lowercase</PROPERTY>
		<PROPERTY>authors AS lowercase</PROPERTY>
		<PROPERTY>venue AS lowercase</PROPERTY>
		<PROPERTY>year AS number</PROPERTY>
		<TYPE>CSV</TYPE>
	</TARGET>
	
	<METRIC>AND(trigram(x.title,y.title)|0.12740796168580043,cosine(x.title,y.title)|0.12740796168580043)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.4093475390922669</THRESHOLD>
		<FILE>dblp-scholar_accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.3</THRESHOLD>
		<FILE>dblp-scholar_reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>
