=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/limes.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT LIMES (PREFIX*, SOURCE, TARGET, (METRIC | MLALGORITHM), ACCEPTANCE, REVIEW, EXECUTION*, GRANULARITY*, OUTPUT*)>
<!ELEMENT PREFIX (NAMESPACE, LABEL)>
<!ELEMENT NAMESPACE (#PCDATA)>
<!ELEMENT LABEL (#PCDATA)>
<!ELEMENT SOURCE (ID, ENDPOINT, GRAPH*, VAR, PAGESIZE, MINOFFSET*, MAXOFFSET*, RESTRICTION+, PROPERTY+, FUNCTION*, OPTIONAL_PROPERTY*, TYPE*)>
<!ELEMENT TARGET (ID, ENDPOINT, GRAPH*, VAR, PAGESIZE, MINOFFSET*, MAXOFFSET*, RESTRICTION+, PROPERTY+, FUNCTION*, OPTIONAL_PROPERTY*, TYPE*)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT RESTRICTION (#PCDATA)>
<!ELEMENT METRIC (#PCDATA)>
<!ELEMENT ACCEPTANCE (THRESHOLD, FILE, RELATION)>
<!ELEMENT REVIEW (THRESHOLD, FILE, RELATION)>
<!ELEMENT RELATION (#PCDATA)>
<!ELEMENT ENDPOINT (#PCDATA)>
<!ELEMENT GRAPH (#PCDATA)>
<!ELEMENT VAR (#PCDATA)>
<!ELEMENT CLASS (#PCDATA)>
<!ELEMENT PROPERTY (#PCDATA)>
<!ELEMENT OPTIONAL_PROPERTY (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT THRESHOLD (#PCDATA)>
<!ELEMENT FILE (#PCDATA)>
<!ELEMENT PAGESIZE (#PCDATA)>
<!ELEMENT MAXOFFSET (#PCDATA)>
<!ELEMENT MINOFFSET (#PCDATA)>
<!ELEMENT GRANULARITY (#PCDATA)>
<!ELEMENT OUTPUT (#PCDATA)>
<!ELEMENT FUNCTION (#PCDATA)>
<!ELEMENT EXECUTION (REWRITER*, PLANNER*, ENGINE*, OPTIMIZATION_TIME*, EXPECTED_SELECTIVITY*)*>
<!ELEMENT REWRITER (#PCDATA)>
<!ELEMENT PLANNER (#PCDATA)>
<!ELEMENT ENGINE (#PCDATA)>
<!ELEMENT MLALGORITHM  (NAME*, TYPE*, TRAINING*, PARAMETER*)*>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT TRAINING (#PCDATA)>
<!ELEMENT PARAMETER  (NAME*, VALUE*)*>
<!ELEMENT VALUE (#PCDATA)>
<!ELEMENT OPTIMIZATION_TIME (#PCDATA)>
<!ELEMENT EXPECTED_SELECTIVITY (#PCDATA)>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/specMovies.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE LIMES
  SYSTEM "limes.dtd">
<LIMES>
   <PREFIX>
      <NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
      <LABEL>rdf</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
      <LABEL>rdfs</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
      <LABEL>owl</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://dbpedia.org/ontology/</NAMESPACE>
      <LABEL>dbpedia-owl</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://dbpedia.org/property/</NAMESPACE>
      <LABEL>dbpedia-prop</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://purl.org/dc/terms/</NAMESPACE>
      <LABEL>dc</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://data.linkedmdb.org/resource/movie/</NAMESPACE>
      <LABEL>linkedmdb</LABEL>
   </PREFIX>
   <PREFIX>
      <NAMESPACE>http://xmlns.com/foaf/0.1/</NAMESPACE>
      <LABEL>foaf</LABEL>
   </PREFIX>
   <SOURCE>
      <ID>dbpedia</ID>
      <ENDPOINT>http://dbpedia.org/sparql</ENDPOINT>
      <GRAPH>http://dbpedia.org</GRAPH>
      <VAR>?a</VAR>
      <PAGESIZE>1000</PAGESIZE>
      <RESTRICTION>?a rdf:type dbpedia-owl:Film</RESTRICTION>
      <PROPERTY>rdfs:label AS lowercase</PROPERTY>
      <PROPERTY>dbpedia-owl:director/rdfs:label AS lowercase</PROPERTY>
      <PROPERTY>dbpedia-owl:releaseDate</PROPERTY>
   </SOURCE>
   <TARGET>
	<ID>linkedmdb</ID>
      <ENDPOINT>http://data.linkedmdb.org/sparql</ENDPOINT>
      <VAR>?b</VAR>
      <PAGESIZE>1000</PAGESIZE>
      <RESTRICTION>?b rdf:type linkedmdb:film</RESTRICTION>
      <RESTRICTION>FILTER(?v2 > "1990-01-01")</RESTRICTION>
      <PROPERTY>rdfs:label AS lowercase</PROPERTY>
      <PROPERTY>linkedmdb:director/rdfs:label AS lowercase</PROPERTY>
      <PROPERTY>linkedmdb:initial_release_date</PROPERTY>  
   </TARGET>
   <METRIC>cosine(a.dbpedia-owl:director/rdfs:label, b.linkedmdb:director/rdfs:label)</METRIC>
   <ACCEPTANCE>
      <THRESHOLD>0.3</THRESHOLD>
      <FILE>acceptSS.nt</FILE>
      <RELATION/>
   </ACCEPTANCE>
   <REVIEW>
      <THRESHOLD>0.3</THRESHOLD>
      <FILE>reviewSS.nt</FILE>
      <RELATION/>
   </REVIEW>
   <EXECUTION>Simple</EXECUTION>
   <OUTPUT>NT</OUTPUT>
</LIMES>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/oaei2014_identity.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.instancematching.org/ontologies/oaei2014#</NAMESPACE>
		<LABEL>oaei2014</LABEL>
	</PREFIX>
<SOURCE>
		<ID>oaei20141</ID>
		<ENDPOINT>src/main/resources/datasets/OAEI2014/oaei2014_identity_a.owl</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type oaei2014:Book</RESTRICTION>
		<PROPERTY>rdfs:label AS lowercase->replace(category,)</PROPERTY>
		<PROPERTY>oaei2014:subject AS lowercase</PROPERTY>
		<PROPERTY>oaei2014:author AS lowercase</PROPERTY>
		<PROPERTY>oaei2014:literaryGenre AS lowercase</PROPERTY>		
		<PROPERTY>oaei2014:genre AS lowercase</PROPERTY>
		<PROPERTY>oaei2014:publisher AS lowercase</PROPERTY>
		<TYPE>RDF/XML</TYPE>
</SOURCE>
	
	<TARGET>
		<ID>oaei20142</ID>
		<ENDPOINT>src/main/resources/datasets/OAEI2014/oaei2014_identity_b.owl</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?y rdf:type oaei2014:Book</RESTRICTION>
		<PROPERTY>rdfs:label AS lowercase->replace(category,)</PROPERTY>
		<PROPERTY>oaei2014:subject AS uriasstring->lowercase</PROPERTY>
		<PROPERTY>oaei2014:author AS lowercase</PROPERTY>
		<PROPERTY>oaei2014:literaryGenre AS lowercase</PROPERTY>		
		<PROPERTY>oaei2014:genre AS lowercase</PROPERTY>
		<PROPERTY>oaei2014:publisher AS lowercase</PROPERTY>
		<TYPE>RDF/XML</TYPE>
	</TARGET>	

	<METRIC>levenshtein(x.rdfs:label, y.rdfs:label)</METRIC>

	<ACCEPTANCE>
		<THRESHOLD>0.2</THRESHOLD>
		<FILE>accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.05</THRESHOLD>
		<FILE>reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	
	<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/persons2_csv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_person1.owl#</NAMESPACE>
		<LABEL>okkamperson1</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_person2.owl#</NAMESPACE>
		<LABEL>okkamperson2</LABEL>
	</PREFIX>
<SOURCE>
		<ID>person11</ID>
		<ENDPOINT>datasets/Persons2/person21.nt.csv</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type http://www.okkam.org/ontology_person1.owl#Person</RESTRICTION>
		<PROPERTY>http://www.okkam.org/ontology_person1.owl#surname AS lowercase</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person1.owl#given_name AS lowercase</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person1.owl#age AS lowercase</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person1.owl#phone_numer</PROPERTY>		
		<PROPERTY>http://www.okkam.org/ontology_person1.owl#soc_sec_id</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person1.owl#has_address AS cleaniri</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person1.owl#date_of_birth AS lowercase</PROPERTY>
		<TYPE>CSV</TYPE>
</SOURCE>
	
	<TARGET>
		<ID>person12</ID>
		<ENDPOINT>datasets/Persons2/person22.nt.csv</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?y rdf:type okkamperson2:Person</RESTRICTION>
		<PROPERTY>http://www.okkam.org/ontology_person2.owl#surname AS lowercase</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person2.owl#given_name AS lowercase</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person2.owl#age AS lowercase</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person2.owl#phone_numer</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person2.owl#has_address AS cleaniri</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person2.owl#soc_sec_id</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_person2.owl#date_of_birth AS lowercase</PROPERTY>
		<TYPE>CSV</TYPE>
	</TARGET>	

	<METRIC>levenshtein(x.http://www.okkam.org/ontology_person1.owl#surname, y.http://www.okkam.org/ontology_person2.owl#surname)</METRIC>

	<ACCEPTANCE>
		<THRESHOLD>0.98</THRESHOLD>
		<FILE>accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.95</THRESHOLD>
		<FILE>reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	
	<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/dbpedia-linkedmdb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>linkedmdb</ID>
		<ENDPOINT>datasets/dbpedia-linkedmdb/source2.csv</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>title AS lowercase->removebraces</PROPERTY>
		<PROPERTY>director AS lowercase->removebraces</PROPERTY>	
		<TYPE>CSV</TYPE>
	</SOURCE>
	<TARGET>
		<ID>dbpedia</ID>
		<ENDPOINT>datasets/dbpedia-linkedmdb/target2.csv</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>title AS lowercase->removebraces</PROPERTY>
		<PROPERTY>director AS lowercase->removebraces</PROPERTY>	
		<TYPE>CSV</TYPE>
	</TARGET>
	
	<METRIC>OR(AND(AND(cosine(x.director,y.director)|0.55,jaccard(x.title,y.title)|0.62)|0.54,AND(cosine(x.director,y.director)|0.54,trigram(x.director,y.director)|0.54)|0.37)|0.69,jaccard(x.title,y.title)|0.62)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.91</THRESHOLD>
		<FILE>dbpedia-linkedmdb_accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.8</THRESHOLD>
		<FILE>dbpedia-linkedmdb_reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
		<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/lgd-lgd-ml.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://geovocab.org/geometry#</NAMESPACE>
		<LABEL>geom</LABEL>
	</PREFIX>
	
	<PREFIX>
		<NAMESPACE>http://www.opengis.net/ont/geosparql#</NAMESPACE>
		<LABEL>geos</LABEL>
	</PREFIX>
	
	<PREFIX>
		<NAMESPACE>http://linkedgeodata.org/ontology/</NAMESPACE>
		<LABEL>lgdo</LABEL>
	</PREFIX>

    <PREFIX>
        <NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
        <LABEL>rdfs</LABEL>
    </PREFIX>
	
	<SOURCE>
		<ID>linkedgeodata</ID>
		<ENDPOINT>http://linkedgeodata.org/sparql</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>2000</PAGESIZE>
		<RESTRICTION>?x a lgdo:RelayBox</RESTRICTION>
		<PROPERTY>geom:geometry/geos:asWKT RENAME polygon</PROPERTY>
	</SOURCE>

	<TARGET>
		<ID>linkedgeodata</ID>
		<ENDPOINT>http://linkedgeodata.org/sparql</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>2000</PAGESIZE>
		<RESTRICTION>?y a lgdo:RelayBox</RESTRICTION>
		<PROPERTY>geom:geometry/geos:asWKT RENAME polygon</PROPERTY>
	</TARGET>
	
	<MLALGORITHM>
		<NAME>wombat simple</NAME>
		<TYPE>unsupervised</TYPE>
		<PARAMETER> 
			<NAME>max execution time in minutes</NAME>
			<VALUE>60</VALUE>
		</PARAMETER>
        <PARAMETER>
            <NAME>beta</NAME>
            <VALUE>5.0</VALUE>
        </PARAMETER>
	</MLALGORITHM>
	
	<ACCEPTANCE>
		<THRESHOLD>0.9</THRESHOLD>
		<FILE>lgd_relaybox_verynear.nt</FILE>
		<RELATION>lgdo:near</RELATION>
	</ACCEPTANCE>
	
	<REVIEW>
		<THRESHOLD>0.5</THRESHOLD>
		<FILE>lgd_relaybox_near.nt</FILE>
		<RELATION>lgdo:near</RELATION>
	</REVIEW>

	<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>

	<OUTPUT>TAB</OUTPUT>
</LIMES>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>    
<!DOCTYPE LIMES SYSTEM "limes.dtd">    
<LIMES>        
	<PREFIX>            
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>            
		<LABEL>owl</LABEL>        
	</PREFIX>        
	<!--<PREFIX>            
		<NAMESPACE>http://zhishi.me/ontology/</NAMESPACE>            
		<LABEL>zhishi</LABEL>        
	</PREFIX>        
	<PREFIX>            
		<NAMESPACE>http://cndbpedia/resource/</NAMESPACE>            
		<LABEL>cndb</LABEL>        
	</PREFIX>
	<PREFIX>            
		<NAMESPACE>http://cndbpedia/ontology/</NAMESPACE>            
		<LABEL>cndbo</LABEL>        
	</PREFIX>
	<PREFIX>            
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>            
		<LABEL>rdfs</LABEL>        
	</PREFIX>-->
	<SOURCE>            
		<ID>plant_baidu</ID>            
		<ENDPOINT>plant_source.csv</ENDPOINT>           
		<VAR>?x</VAR>            
		<PAGESIZE>-1</PAGESIZE>            
		<RESTRICTION></RESTRICTION>            
		<PROPERTY>name as lowercase</PROPERTY>            
		<TYPE>csv</TYPE>        
	</SOURCE>        
	<TARGET>            
		<ID>plant_wiki</ID>           
		<ENDPOINT>plant_target.csv</ENDPOINT>            
		<VAR>?y</VAR>            
		<PAGESIZE>-1</PAGESIZE>            
		<RESTRICTION></RESTRICTION>            
		<PROPERTY>name as lowercase</PROPERTY>                    
		<TYPE>csv</TYPE>        
	</TARGET>        
	<METRIC>Cosine(x.name, y.name) | 0.8</METRIC>
	<!--<METRIC>jarowinkler(x.name,y.name)</METRIC>  -->      
	<ACCEPTANCE>            
		<THRESHOLD>0.9</THRESHOLD>            
		<FILE>accept_result.nt</FILE>            
		<RELATION>owl:sameAs</RELATION>        
	</ACCEPTANCE>        
	<REVIEW>            
		<THRESHOLD>0.5</THRESHOLD>            
		<FILE>review_result.nt</FILE>            
		<RELATION>owl:sameAs</RELATION>        
	</REVIEW>
	<EXECUTION>            
		<REWRITER>default</REWRITER>            
		<PLANNER>default</PLANNER>            
		<ENGINE>default</ENGINE>        
	</EXECUTION>

	<OUTPUT>TAB</OUTPUT>    
</LIMES>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/restaurants.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2000/01/rdf-schema#</NAMESPACE>
		<LABEL>rdfs</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_person1.owl#</NAMESPACE>
		<LABEL>okkamperson1</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_person2.owl#</NAMESPACE>
		<LABEL>okkamperson2</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_restaurant2.owl#</NAMESPACE>
		<LABEL>okkamrestaurant2</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_restaurant1.owl#</NAMESPACE>
		<LABEL>okkamrestaurant1</LABEL>
	</PREFIX>
<SOURCE>
		<ID>restaurant1</ID>
		<ENDPOINT>datasets/Restaurants/restaurant1.nt</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type http://www.okkam.org/ontology_restaurant1.owl#Restaurant</RESTRICTION>
		<PROPERTY>http://www.okkam.org/ontology_restaurant1.owl#has_address AS lowercase</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_restaurant1.owl#category AS lowercase</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_restaurant1.owl#phone_number</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_restaurant1.owl#name AS lowercase</PROPERTY>

		<TYPE>N3</TYPE>
</SOURCE>
	
	<TARGET>
		<ID>restaurant2</ID>
		<ENDPOINT>datasets/Restaurants/restaurant2.nt</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?x rdf:type http://www.okkam.org/ontology_restaurant2.owl#Restaurant</RESTRICTION>
		<PROPERTY>http://www.okkam.org/ontology_restaurant2.owl#has_address AS lowercase</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_restaurant2.owl#phone_number</PROPERTY>
		<PROPERTY>http://www.okkam.org/ontology_restaurant2.owl#name AS lowercase</PROPERTY>

		<TYPE>N3</TYPE>
	</TARGET>	

	<METRIC>levenshtein(x.http://www.okkam.org/ontology_restaurant1.owl#name, y.http://www.okkam.org/ontology_restaurant2.owl#name)</METRIC>

	<ACCEPTANCE>
		<THRESHOLD>0.98</THRESHOLD>
		<FILE>accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.95</THRESHOLD>
		<FILE>reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	
		<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>

=== wvirtue/Plant-Knowledge-Graph/Plant_KnowledgeGraph/src/com/gzu/knowledgeFusion/LIMES-Plant/limes-core/src/main/resources/datasets/Amazon-GoogleProducts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/2002/07/owl#</NAMESPACE>
		<LABEL>owl</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>amazon</ID>
		<ENDPOINT>datasets/Amazon-GoogleProducts/Amazon.csv</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>title AS lowercase</PROPERTY>
		<PROPERTY>description AS lowercase</PROPERTY>
		<PROPERTY>manufacturer AS lowercase</PROPERTY>
		<PROPERTY>price AS number</PROPERTY>
		<TYPE>CSV</TYPE>
	</SOURCE>
	<TARGET>
		<ID>googleprod</ID>
		<ENDPOINT>datasets/Amazon-GoogleProducts/GoogleProducts.csv</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>-1</PAGESIZE>
		<RESTRICTION></RESTRICTION>
		<PROPERTY>name AS lowercase</PROPERTY>
		<PROPERTY>description AS lowercase</PROPERTY>
		<PROPERTY>manufacturer AS lowercase</PROPERTY>
		<PROPERTY>price AS number</PROPERTY>
		<TYPE>CSV</TYPE>
	</TARGET>
	
	<METRIC>OR(cosine(x.title,y.name)|0.374142355670193,cosine(x.title,y.description)|0.39117335063587566)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.6065832358304951</THRESHOLD>
		<FILE>pub_accepted.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.5</THRESHOLD>
		<FILE>pub_reviewme.txt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>N3</OUTPUT>
</LIMES>
